"""empty message

Revision ID: 1ba62d9d0949
Revises: 3adba7159fdd
Create Date: 2019-01-04 15:19:29.959706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ba62d9d0949'
down_revision = '3adba7159fdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('modified_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'modified_at')
    # ### end Alembic commands ###
