"""conversation table

Revision ID: 3adba7159fdd
Revises: 
Create Date: 2019-01-04 14:17:12.061123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3adba7159fdd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('de', sa.String(length=20), nullable=True),
    sa.Column('para', sa.String(length=20), nullable=True),
    sa.Column('mensaje', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('conversations')
    # ### end Alembic commands ###
